python-targets:
    - 3
doc-warnings: no
test-warnings: no
strictness: low
max-line-length: 120
autodetect: yes
ignore-paths:
    - doc
pylint:
  disable:
    - E0602
    - E1002
    - E1004
    - W0512
    - W0105
    - MC0000
pep8:
  disable:
    - W191
    - E126
    - E127
    - E128
    - E223
