doc-warnings: no
test-warnings: no
strictness: low
max-line-length: 120
autodetect: yes
ignore-paths:
    - doc
pylint:
  disable:
    - E1002
    - E1004
    - W0512
    - W0105
pep8:
  disable:
    - E1004
    - W191
    - E126
    - E127
    - E128
    - E223
